language: cpp

compiler:
  - gcc
  - clang

sudo: false

# Handle git submodules yourself
git:
    submodules: false

before_script:
  - CC_Cmp=${CC}
  - CXX_Cmp=${CXX}
  - GCC_Cmp=${MY_GCC_VERSION}
  - CLANG_Cmp=${MY_CLANG_VERSION}
  - MY_CXX_Compiler=""
  - MY_CC_Compiler=""
  - chmod a+x ./ci/travis.before_install.sh
  - ./ci/travis.before_install.sh
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER=${MY_CXX_Compiler} -DCMAKE_C_COMPILER=${MY_CC_Compiler} ..

script: cd build && make

os:
  - linux
  - osx

env:
  global:
    - MY_GCC_VERSION="5"
    - MY_CLANG_VERSION="3.7"
  matrix:
    - BUILD_TYPE=Debug
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - boost-latest
    packages:
    - cmake
    - clang-3.7
    - g++-5
    - libboost1.55-all-dev
