language: cpp

compiler:
  - gcc
  - clang

sudo: false

# Handle git submodules yourself
git:
    submodules: false

before_script:
  - if [ "$TRAVIS_OS_NAME"=="linux" ] && [ "$CXX" == "g++" ]; then export CXX_COMPILER=$(which g++-${GCC_VERSION}); fi
  - if [ "$TRAVIS_OS_NAME"=="linux" ] && [ "$CXX" == "g++" ]; then export C_COMPILER=$(which gcc-${GCC_VERSION}); fi
  - if [ "$TRAVIS_OS_NAME"=="linux" ] && [ "$CXX" != "g++" ]; then export CXX_COMPILER=$(which clang++-${CLANG_VERSION}); fi
  - if [ "$TRAVIS_OS_NAME"=="linux" ] && [ "$CXX" != "g++" ]; then export C_COMPILER=$(which clang-${CLANG_VERSION}); fi
  - mkdir build
  - cd build
  - cmake --version
  - $CXX_COMPILER --version
  - $C_COMPILER --version
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_C_COMPILER=${C_COMPILER} ..

script: make

os:
  - linux

env:
  global:
    - GCC_VERSION="5"
    - CLANG_VERSION="3.6"
  matrix:
    - BUILD_TYPE=Debug
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - boost-latest
    packages:
    - cmake
    - clang-3.6
    - g++-5
    - libboost1.55-all-dev
