language: cpp

compiler:
  - gcc
  - clang

sudo: false

# Handle git submodules yourself
git:
    submodules: false

before_script:
  - if [ "$CXX" == "g++" ]; then  MY_CXX_Compiler=g++-${MY_GCC_VERSION}; fi
  - if [ "$CXX" == "clang++" ]; then MY_CXX_Compiler=clang++-${MY_CLANG_VERSION}; fi
  - if [ "$CC" == "gcc" ]; then  MY_CC_Compiler=gcc-${MY_GCC_VERSION}; fi
  - if [ "$CC" == "clang" ]; then MY_CC_Compiler=clang-${MY_CLANG_VERSION}; fi
  - mkdir build
  - cd build
  - cmake --version
  - echo ${MY_CXX_Compiler}
  - echo ${MY_CC_Compiler}
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER=${MY_CXX_Compiler} -DCMAKE_C_COMPILER=${MY_CC_Compiler} ..

script: cd build && make

os:
  - linux

env:
  global:
    - MY_GCC_VERSION="5"
    - MY_CLANG_VERSION="3.7"
  matrix:
    - BUILD_TYPE=Debug
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    - boost-latest
    packages:
    - cmake
    - clang-3.7
    - g++-5
    - libboost-all-dev
