language: cpp

compiler:
  - gcc
  - clang

sudo: false

# Handle git submodules yourself
git:
    submodules: false

before_script:
  - if [ "$TRAVIS_OS_NAME"=="linux" ] && [ "$CXX" == "g++" ]; then export CXX_Compiler=$(which g++-${GCC_VERSION}); fi
  - if [ "$TRAVIS_OS_NAME"=="linux" ] && [ "$CXX" == "g++" ]; then export CC_Compiler=$(which gcc-${GCC_VERSION}); fi
  - if [ "$TRAVIS_OS_NAME"=="linux" ] && [ "$CXX" != "g++" ]; then export CXX_Compiler=$(which clang++-${CLANG_VERSION}); fi
  - if [ "$TRAVIS_OS_NAME"=="linux" ] && [ "$CXX" != "g++" ]; then export CC_Compiler=$(which clang-${CLANG_VERSION}); fi
  - if [ "$TRAVIS_OS_NAME"=="osx" ]; then export CXX_Compiler=${CXX}; fi
  - if [ "$TRAVIS_OS_NAME"=="osx" ]; then export CC_Compiler=${CC}; fi
  - mkdir build
  - cd build
  - ${CXX_Compiler} --version
  - ${CC_Compiler} --version
  - cmake --version
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER=${CXX_Compiler} -DCMAKE_C_COMPILER=${CC_Compiler} ..

script: make

os:
  - linux
  - osx

env:
  global:
    - GCC_VERSION="5"
    - CLANG_VERSION="3.6"
  matrix:
    - BUILD_TYPE=Debug
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - boost-latest
    packages:
    - cmake
    - clang-3.6
    - g++-5
    - libboost1.55-all-dev
