language: cpp

compiler:
  - gcc
  - clang

sudo: false

# Handle git submodules yourself
git:
    submodules: false

before_script:
  - chmod a+x ./ci/travis.before_install.sh
  - ./ci/travis.before_install.sh

script: make

os:
  - linux
  - osx

env:
  global:
    - MY_GCC_VERSION="5"
    - MY_CLANG_VERSION="3.7"
  matrix:
    - BUILD_TYPE=Debug
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - boost-latest
    packages:
    - cmake
    - clang-3.7
    - g++-5
    - libboost1.55-all-dev
