language: cpp

compiler:
  - gcc
  - clang

sudo: false

# Handle git submodules yourself
git:
    submodules: false

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - $CXX --version
  - $CC --version
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_C_COMPILER=${CC} ..

script: make

os:
  - linux
  - osx

env:
  global:
    - GCC_VERSION="5"
    - CLANG_VERSION="3.6"
  matrix:
    - BUILD_TYPE=Debug
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - boost-latest
    packages:
    - cmake
    - clang-3.6
    - g++-5
    - libboost1.55-all-dev
