language: cpp

compiler:
  - gcc
  - clang

sudo: false

# Handle git submodules yourself
git:
    submodules: false

before_script:
  - echo ${TRAVIS_OS_NAME}
  - if [ "$TRAVIS_OS_NAME"=="linux" ] && [ "$CXX" == "g++" ]; then export MY_CXX_Compiler=$(which g++-${MY_GCC_VERSION}); fi
  - if [ "$TRAVIS_OS_NAME"=="linux" ] && [ "$CXX" == "g++" ]; then export MY_CC_Compiler=$(which gcc-${MY_GCC_VERSION}); fi
  - if [ "$TRAVIS_OS_NAME"=="linux" ] && [ "$CXX" != "g++" ]; then export MY_CXX_Compiler=$(which clang++-${MY_CLANG_VERSION}); fi
  - if [ "$TRAVIS_OS_NAME"=="linux" ] && [ "$CXX" != "g++" ]; then export MY_CC_Compiler=$(which clang-${MY_CLANG_VERSION}); fi
  - if [ "$TRAVIS_OS_NAME"=="osx" ]; then export MY_CC_Compiler=${CXX}; fi
  - if [ "$TRAVIS_OS_NAME"=="osx" ]; then export MY_CC_Compiler=${CC}; fi
  - if [ "$TRAVIS_OS_NAME"=="osx" ]; then brew update clang; fi
  - mkdir build
  - cd build
  - ${MY_CXX_Compiler} --version
  - ${MY_CC_Compiler} --version
  - cmake --version
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER=${MY_CXX_Compiler} -DCMAKE_C_COMPILER=${MY_CC_Compiler} ..

script: make

os:
  - linux
  - osx

env:
  global:
    - MY_GCC_VERSION="5"
    - MY_CLANG_VERSION="3.7"
  matrix:
    - BUILD_TYPE=Debug
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - boost-latest
    packages:
    - cmake
    - clang-3.7
    - g++-5
    - libboost1.55-all-dev
